### ISSUE TITLE
Add Razorpay Checkout Integration

### ISSUE THREAD

**Issue by dharmikbhesaniya** [dharmikbhesaniya/unify-pay-flex#1]
We would like to integrate Razorpay's Checkout functionality into our project. Razorpay Checkout provides a seamless payment experience for users, allowing them to make payments directly from the checkout page.

**Comment by abhipatel80** [comment]
I have integrated the Razorpay gateway and published the package.
https://www.npmjs.com/package/unify-pay-flex

**Comment by dharmikbhesaniya** [comment]
solve this issue
